version: '3'

services:
  postgres:
    container_name: 'go_database'
    image: 'postgres:11'
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  redis:
    container_name: go_redis
    image: 'redis:alpine'
    command: redis-server --requirepass ${REDIS_ROOT_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'

  mongo:
    container_name: go_mongo
    image: 'mongo'
    env_file: .env
    command: 'mongod --auth --storageEngine wiredTiger'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodata:/data/db'

volumes:
  pgdata:
  redisdata:
  mongodata:
